services:
  frontend:
    build:
      context: ./delivery-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
    - "3000"
    networks:
      - app-network

  backend:
    build:
      context: ./delivery-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
    - "5000"
    # Coolify will inject the environment variables at runtime
    # but for local testing, uncomment the line below:
    #env_file: ./delivery-backend/.env

    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    expose:
      - "80"
    #volumes:
    # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
